### ISSUE TITLE
Server Error (500) when click on Finish Experiment

### ISSUE THREAD

**Issue by radinsky** [tcsvn/activity-assistant#8] opened 2021-01-04 22:40 UTC
Tried to run an experiment, cannot terminate it - when clicking on Finish Experiment getting Server Error (500) 

![image](https://user-images.githubusercontent.com/4540268/103586781-79f1ba00-4eee-11eb-983f-f451bd631f17.png)

![image](https://user-images.githubusercontent.com/4540268/103586816-8f66e400-4eee-11eb-9c62-c9be28e0946d.png)

**Comment by tcsvn** [comment] 2021-01-05 08:48
Thank you for your response and you taking interest in the project. Would you please provide me some additional information to tackle the problem. 

- What is your arch (armv7, amd64, aarch64) or what device do you run Home Assistant on (raspberry pi, ...)?  
- For how long did you run the experiment? 
- Did you restart your machine during the experiment? 
  - This provides me with information if maybe some environment changed e.g hass api keys
- The Addon reports error information on the log tab. It would be helpful if you reproduce the error, copy the error message and post it here. 
- Does it work to export data while you run an experiment?
  - exporting data uses some of the same mechanisms as finishing an experiment


My guess is that somehow the communication between Home Assistant and the Addon fails. 

Thank you for your time and I am looking forward to your reply.

**Comment by radinsky** [comment] 2021-01-05 08:56
Hi, please see inline:

- What is your arch (armv7, amd64, aarch64) or what device do you run Home Assistant on (raspberry pi, ...)?
NUC w Ubuntu(64), Docker, HA is supervised
- For how long did you run the experiment?
>10 seconds. just realized I have nothing to do and wanted to stop/cancel it
- Did you restart your machine during the experiment?
No
- This provides me with information if maybe some environment changed e.g hass api keys
No
- The Addon reports error information on the log tab. It would be helpful if you reproduce the error, copy the error message and post it here.
Once the addon started, there was no new logs... attaching the entire log
```

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
No changes detected
Operations to perform:
  Synchronize unmigrated apps: backend, frontend, messages, qr_code, rest_framework, staticfiles
  Apply all migrations: admin, auth, authtoken, contenttypes, sessions
Synchronizing apps without migrations:
  Creating tables...
    Creating table backend_dataset
    Creating table backend_personstatistic
    Creating table backend_person
    Creating table backend_location
    Creating table backend_edge
    Creating table backend_device
    Creating table backend_activity
    Creating table backend_activityprediction
    Creating table backend_syntheticactivity
    Creating table backend_smartphone
    Creating table backend_model
    Creating table backend_realtimenode
    Creating table backend_deviceprediction
    Creating table backend_server
    Running deferred SQL...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying sessions.0001_initial... OK
Installed 1 object(s) from 1 fixture(s)
[2021-01-05 00:23:12 +0200] [212] [INFO] Starting gunicorn 20.0.4
[2021-01-05 00:23:12 +0200] [212] [INFO] Listening at: unix:/tmp/gunicorn.sock (212)
[2021-01-05 00:23:12 +0200] [212] [INFO] Using worker: sync
[2021-01-05 00:23:12 +0200] [219] [INFO] Booting worker with pid: 219
Registration of a service, press Ctrl-C to exit...
(SIGTERM) terminating the process
Unregistering...
[Errno 2] No such file or directory: '/config/config/core/../../../customization/customize_global.yaml'
Registration of a service, press Ctrl-C to exit...
(SIGTERM) terminating the process
Unregistering...
```
- Does it work to export data while you run an experiment?
didn't tried
- exporting data uses some of the same mechanisms as finishing an experiment

**Comment by tcsvn** [comment] 2021-01-05 09:20
First of all thanks for your detailed answer. 

> just realized I have nothing to do 
Yeah, happened to me as well ^^ Also during an experiment it sometimes felt unnatural to be forced to always perform an activity. 

The error seems to occur when activity-assistant searches for your database.

 Would you please navigate to `http://youraddress:port/api/server/1` and report the field value `hass_db_url` ?

**Comment by radinsky** [comment] 2021-01-05 15:17
My hass_db_url appears to be null ..

`  "hass_db_url": null,`

**Comment by tcsvn** [comment] 2021-01-08 19:40
I am not capable of reproducing the error, because I currently have no available linux machine to test [homeassistant-supervised](https://github.com/home-assistant/supervised-installer) on. So let's try to make this work from remote :). I have narrowed down the problem to a codeblock that produces the error (where activity-assistant determines your database url). 

I have prepared a more verbose addon version for you on the edge channel. If you don't mind go to the addon repository (you may have to reload the repositories), download the "activity-assistant (edge)" addon, reproduce the error and post the logs. This should hopefully be sufficient for me to fix the bug. 

Could you also please specify 
- what database are you using?
- do you have the "recorder" integration installed?
- if there is a db_url entry please post it (you should of course blackout the passwords ;))

Thanks for your reply and patients!

**Comment by tcsvn** [comment] 2023-02-02 10:19
Should be fixed with new version

**Closed by tcsvn** 2023-02-02 10:19 UTC
Labels: bug
