### ISSUE TITLE
Addon refused to connect

### ISSUE THREAD

**Issue by radinsky** [tcsvn/activity-assistant#2] opened 2020-12-15 13:24 UTC
Cannot get addon to work, getting "refused to connect":
![image](https://user-images.githubusercontent.com/4540268/102220373-62c03d80-3ee9-11eb-966e-4cd4858dd18a.png)

Installed using supervisor and https://github.com/tcsvn/hassio-activity-assistant repo 

Boot Log:
```

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
No changes detected
Operations to perform:
  Synchronize unmigrated apps: backend, frontend, messages, qr_code, rest_framework, staticfiles
  Apply all migrations: admin, auth, authtoken, contenttypes, sessions
Synchronizing apps without migrations:
  Creating tables...
    Creating table backend_dataset
    Creating table backend_personstatistic
    Creating table backend_person
    Creating table backend_location
    Creating table backend_edge
    Creating table backend_device
    Creating table backend_activity
    Creating table backend_activityprediction
    Creating table backend_syntheticactivity
    Creating table backend_smartphone
    Creating table backend_model
    Creating table backend_realtimenode
    Creating table backend_deviceprediction
    Creating table backend_server
    Running deferred SQL...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying sessions.0001_initial... OK
CommandError: No fixture named 'inital_server' found.
[2020-12-15 15:17:08 +0200] [187] [INFO] Starting gunicorn 20.0.4
[2020-12-15 15:17:08 +0200] [187] [INFO] Listening at: http://0.0.0.0:8000 (187)
[2020-12-15 15:17:08 +0200] [187] [INFO] Using worker: sync
[2020-12-15 15:17:08 +0200] [212] [INFO] Booting worker with pid: 212

```
After I click on [OPEN WEB UI] I get `XXXX.duckdns.org refused to connect.`

And in the log I see:
```
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/activity_assistant/web/frontend/views/setup.py", line 160, in get
    srv = Server.objects.all()[0]
  File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 325, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
```

**Comment by tcsvn** [comment] 2020-12-17 13:09
Hey there, thanks for the feedback. I am going to look into this issue as soon as possible! Should be fixed before the weekend.

**Comment by tcsvn** [comment] 2020-12-21 16:50
So I think I fixed the Issue. I can only test this myself for the armv7 or amd64 distributions. If the Issue isn't resolved for you, could you please specify the distribution you are using? For now getting the changes requires you to reinstall the Addon. I will add versioning and updates in a few days.

**Comment by radinsky** [comment] 2020-12-21 17:57
I'm on nuc ubuntu 64 supervised

Reinstalled the addon, all working perfect! Thanks for a quick fix!
![image](https://user-images.githubusercontent.com/4540268/102807066-ab369a00-43c6-11eb-848b-730a1d90e3b9.png)

--
--

@tcsvn can you tell please if your video from the conference available?
I want to view it again before I ask more question.. Thanks!!

**Comment by tcsvn** [comment] 2020-12-21 21:54
Hey @radinsky ,

I am happy you're taking interest in the project. Feel free to ask me anything via email. I don't know when the video will be uploaded.

**Closed by tcsvn** 2020-12-21 21:54 UTC
